spring.application.name=bracketbackend
spring.security.user.name=admin
spring.security.user.password=admin123

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT key configuration
jwt.private-key=classpath:jwt/app.key
jwt.public-key=classpath:jwt/app.pub
jwt.ttl=15m