services:
  bracketfrontend:
    image: bracketfrontend
    build:
      context: bracket-frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
    volumes:
      - ./bracket-frontend/src:/app/src
      - ./bracket-frontend/angular.json:/app/angular.json
  bracketbackend:
    image: bracketbackend
    build:
      context: bracket-backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
